### ISSUE TITLE
Wrong timestamp conversion when writing TTF

### ISSUE THREAD

**Issue by sigprof** [ot-builder/monorepo#89]
The code in `packages/bin-composite-types/src/long-date-time.ts` converts the timestamp to the format used in TTF files using the offset calculated as a difference of `Date` values:
```js
const EpochDifference = new Date(1970, 1, 1).getTime() - new Date(1904, 1, 1).getTime();
```
However, the `Date(y, m, d)` constructor takes values in the local time zone, not UTC, and the time zone offset for 1970-01-01 and 1904-01-01 might not be identical, therefore `EpochDifference` may be calculated wrongly depending on the local time zone config.

One way to fix that problem is to construct these `Date` objects from strings — apparently that variation of constructor assumes UTC and therefore works properly with any local time zone:
```js
const EpochDifference = new Date("1970-01-01").getTime() - new Date("1904-01-01").getTime();
```
But I'm not really sure that it's the proper JS style for doing that.

**Comment by CyanoHao** [comment]
Next release will have this fix.
